#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config window_shadow                off
yabai -m config active_window_border_color   0xff008c01
yabai -m config normal_window_border_color   0x01000002
yabai -m config window_border_width          10
yabai -m config active_window_opacity        3.0
yabai -m config normal_window_opacity        3.0
yabai -m config split_ratio                  2.50
yabai -m config auto_balance                 off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10
yabai -m config external_bar main:0:0

# space 4: Development
yabai -m rule --add app="Alacritty" space=^3 display=1
yabai -m rule --add app="Paw" space=^4

# space 5: web and email
yabai -m rule --add app="Brave" space=^5
yabai -m rule --add app="Spark" space=^5

# space 6: floating
yabai -m space 6 --layout stack
yabai -m space 6 --padding abs:8:8:8:450
yabai -m rule --add app="Parallels Desktop" title="Control Center" space=^6 manage=off
yabai -m rule --add app="Parallels Desktop" space=^6
yabai -m rule --add app="Adobe Photoshop" space=^6
yabai -m rule --add app="DataGrip" space=^6

# display 2: off-stream and out of the way
yabai -m rule --add app="Discord" display=2
yabai -m rule --add app="Spotify" display=2
yabai -m rule --add app="OBS" display=2

# things which create floating children
yabai -m rule --add app="System Preferences" manage=off
