#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:0:0
# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                on
yabai -m config window_border_width          9
yabai -m config active_window_border_color   0xff3d455b
yabai -m config normal_window_border_color   0xff353943
yabai -m config insert_feedback_color        0xaa353943
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               control
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0


# window rules
yabai -m rule --add app="^Microsoft Outlook$"
yabai -m rule --add app="^Inkdrop$" manage=off
yabai -m rule --add app="^Spotify$" manage=off 
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="app" title="Sumbox" manage=off
yabai -m rule --add title="Rithul Kamesh" manage=off
yabai -m rule --add app="Surfshark" manage=off
yabai -m rule --add app="Lunar Client" manage=off
yabai -m rule --add app='IntelliJ IDEA' title='^$' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Project Structure' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Preferences' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Edit configuration' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Welcome to IntelliJ Idea^$' manage=off
yabai -m rule --add app="Authy Desktop" manage=off
yabai -m rule --add app="Finder" manage=off


# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."
