#!/usr/bin/env sh

spacebar -m config text_font "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font "MesloLGS Nerd Font Mono:Bold:16.0"
spacebar -m config background_color 0xff282c3f
spacebar -m config foreground_color 0xff979eab
spacebar -m config space_icon_strip      
spacebar -m config power_icon_strip  
spacebar -m config space_icon 
spacebar -m config clock_icon 
spacebar -m config clock_format "%a %R"

echo "spacebar configuration loaded.."

